### PR TITLE
Maf concat

### PR DESCRIPTION
**Pull request by carmelinacharalambous**
### Maf concert pv module ###

* Takes in a list of maf files
* Combines maf files based on minimum required columns for a MAF file 
* outputs combined maf file

### CODE REVIEW

**Comment by buehlere** [comment]
Things to do: 
- add argument (@carmelinacharalambous )
- clean up cases and logging (@buehlere and @carmelinacharalambous )
- restructure commands around maf. See (https://lucid.app/lucidchart/5e7ee89d-ab30-412a-b077-b29035f44ac6/edit?invitationId=inv_4a7ba6e7-6296-4441-a474-40605b76e47a&page=.C9a5LZ.mnBZ#) (@buehlere)

**Comment by buehlere** [comment]
@carmelinacharalambous and @rhshah I think this is ready for review. Let me know your thoughts! 

Here are the two basic test cases I tried: 

```
pv maf concat -f /Users/ebuehler/Downloads/C-3WHLWR-L001-d.DONOR22-TP.combined-variants.vep_keptrmv_taggedHotspots_fillout_filtered.maf -f /Users/ebuehler/Downloads/C-3WHLWR-L002-d.DONOR22-TP.combined-variants.vep_keptrmv_taggedHotspots_fillout_filtered.maf
```
where each -f is a simple maf file. 
```
pv maf concat --paths test.txt
```
where test.txt is a text file where each row is a maf path and a ',' denotes a new line.

**Comment by carmelinacharalambous** [comment]
@buehlere Thanks, I will add the additional column fields required

**Comment by buehlere** [comment]
also I added tests in that work, but need to de-identify the test data before pushing everything.

**Comment by rhshah** [comment]
> where test.txt is a text file where each row is a maf path and a ',' denotes a new line.

`,` not sure why is this needed

**Comment by buehlere** [comment]
> > where test.txt is a text file where each row is a maf path and a ',' denotes a new line.
> 
> `,` not sure why is this needed

so format for the `.txt` should be: 
```
/path/to/C-1234-L001-d.maf
/path/to/Downloads/C-1234-L002-d.maf
```

**Comment by buehlere** [comment]
Tests are working in most recent commit.

**Comment by buehlere** [comment]
Additional Features: 
- Deduplicate option (remove sample specific columns, and squash to unique). @carmelinacharalambous what columns are sample specific? 
- should work with extensions txt and maf
- Check for standard minimum maf headers. If using non-standard minimum, header file must be provided.

**Pull request closed without merging**
